version: "3.9"

services:
  glyconformer:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PYTHON_VERSION: 3.10.1
    container_name: glyconformer
    ports:
      - "8888:8888"
    volumes:
      - .:/app
    working_dir: /app
    command: >
      jupyter notebook
      --ip=0.0.0.0
      --port=8888
      --NotebookApp.token=''
      --NotebookApp.password=''
      --no-browser
      --allow-root
      --NotebookApp.notebook_dir=/app
